add env distintion and update TLS info
stackblitz/docs pull request #147
Opened 2023-08-21 14:34 UTC by purplem1lk

# PR Description

This PR fixes the issue number: 

### Summary of my changes and explanation of my decisions

- 
-
-

### Self-check

Please check all that apply:

- [ ] My code follows the style guidelines of this project
- [ ] I have reviewed my code or content update and edited it to the best of my abilities
- [ ] I have commented my code, particularly in hard-to-understand areas; my comments are concise

### Contributors list

Would you like your contribution to be celebrated? Please check all that apply:

- [ ] I would like to be featured on the future contributors list in the README. If so, please tell us:
  - what name you'd like to be shown there?
  - we usually link github profile pic -- is that ok? If not, provide another url: 
  - we usually link your github profile but if you have a portfolio page, provide a link:

- [ ] I would like to get a shoutout in the next monthly updates post. If so, please provide your twitter handle (or we will link to your GitHub profile).

⚡️ ⚡️ ⚡️  Thank you for contributing to StackBlitz ⚡️ ⚡️ ⚡️

2023-08-22 21:12 UTC, kc0tlh commented on docs/guides/user-guide/available-environments.md
> +You can also check in the project settings in the left pane of any StackBlitz project. When you click the gear icon, the top of the settings pane will display "WebContainers" for WebContainer-based p
Only true in the Classic Editor

2023-08-22 21:13 UTC, kc0tlh commented on docs/guides/user-guide/available-environments.md
> +You can also check in the project settings in the left pane of any StackBlitz project. When you click the gear icon, the top of the settings pane will display "WebContainers" for WebContainer-based p
Only true for the Classic Editor

2023-08-22 21:14 UTC, kc0tlh commented on docs/guides/user-guide/available-environments.md
> +Currently, the terminal is only available in projects which use the WebContainers execution environment. There is no way to automatically convert from one execution environment to another.
Don't tell them they can't autop convert without providing the workaround. Probably best ot just not mention it at all

2023-08-22 21:15 UTC, kc0tlh requested changes
See comments

2023-08-24 19:49 UTC, purplem1lk commented
@kc0tlh feedback has been incorporated. @sulco PR is ready for you when you are! 🙏

2023-09-07 19:44 UTC, purplem1lk commented on docs/guides/user-guide/available-environments.md
> +You can also check in the project settings in the left pane of any StackBlitz project. When you click the gear icon, the top of the settings pane will display "WebContainers" for WebContainer-based p
Also add Codeflow behavior and screenshots

2023-09-21 14:03 UTC, purplem1lk commented
@kc0tlh ⬆️ Pinging for review to enable merging.

2023-10-06 19:59 UTC, kc0tlh approved these changes

2023-10-09 17:49 UTC, peter-zawistowicz commented
@kc0tlh this looks great! the one question I had was whether the title is explicit enough. maybe something like: "Runtimes: EngineBlock vs. WebContainers" ?

2023-10-10 17:27 UTC, merged

2023-10-14 02:15 UTC, kc0tlh commented
Re-created and merge this branch in PR #160