Update docs/guides/user-guide/general-faqs.md
stackblitz/docs pull request #177
Opened 2023-11-04 16:28 UTC by endocytosis

Broken links and grammar fixes

2023-11-16 23:50 UTC, kc0tlh commented on docs/guides/user-guide/general-faqs.md
> +Web Publisher is a single file editor and publishing tools that can be used for smaller or text-based changes such as editiong documentation or blogs. Web Publisher uses Codeflow technology that allo
Adding a typo I believe :)

2023-11-16 23:50 UTC, kc0tlh commented on docs/guides/user-guide/general-faqs.md
> +Our JavaScript SDK (software development kit) allows users to create Classic Editor projects to be opened in a new window or embedded in your docs, example pages, or blog posts. The SDK can be used t
Adding a typo I believe :)

2023-11-16 23:51 UTC, kc0tlh commented on docs/guides/user-guide/general-faqs.md
> +This product is ideal for organizations wanting to build completely custom user interfaces powered by Node.js without needed in use virtual machines, servers, or docker containers.
Disagree with this edit. Original was better

2023-11-16 23:52 UTC, kc0tlh commented on docs/guides/user-guide/general-faqs.md
> +We do offer [WebContainer API](webcontainers.io) licenses for organizations wanting to use WebContainer technology for production usage in a for-profit setting. Check out [webcontainers.io](webcontai
The second link should actually link to https://webcontainers.io/enterprise

2023-11-16 23:52 UTC, kc0tlh requested changes
Please address issues mentioned in comments

2023-11-25 20:52 UTC, endocytosis reviewed
Addressed grammar and link fixes.

2023-12-12 00:06 UTC, kc0tlh approved these changes

2023-12-12 00:06 UTC, merged